import Link from "next/link";
const chapters: [string, string[]][]=[
 ["Getting started",["Create an account from the landing page and confirm your email if asked.","Complete the four setup steps. This creates the farm workspace but no sample records.","Use the Start here checklist on Overview. Each completed item means a real record exists.","Return to Overview at any time to see what is still missing."]],
 ["Livestock",["Choose Livestock, then Register animal.","Use a permanent tag or ear-tag number so the animal remains identifiable.","Record current weight and daily feed when known; leave nothing guessed.","Open any animal row to review every saved field.","For sold, deceased or transferred animals, keep the historic record and use its status rather than creating a duplicate."]],
 ["Workforce and tasks",["Add every worker once, with the role they actually perform.","Create a task from the Overview setup guide and use a clear action title.","Use Scheduled for future work, In progress while active, Blocked when something prevents completion, and Completed only when verified.","Do not put passwords, medical details or private payroll information in task notes."]],
 ["Resources",["Log each meter, delivery or inventory measurement as a resource reading.","Choose a consistent zone name such as North Barn or Well 1.","Always include the unit—litres, kWh, kilograms or another exact unit.","Record readings at consistent intervals before interpreting trends.","A sudden change is a reason to inspect the farm; it is not automatically a fault."]],
 ["Finance",["Record income as Income and purchases, bills or payroll as Expense.","Use consistent categories so later summaries remain meaningful.","The counterparty is the supplier, employee, customer or institution involved.","Verdant is an operating record, not a replacement for regulated tax or accounting advice."]],
 ["Analytics",["Analytics remains intentionally empty until operational records exist.","Displayed totals are calculated from your farm records only.","For comparable trends, keep units and recording frequency consistent.","Never make an animal-care or financial decision from one measurement alone."]],
 ["Automations",["Create a rule with a plain-language name and a specific trigger.","Keep high-impact actions—animal treatment, payroll and purchases—under human review.","Review a rule whenever the related farm process changes."]],
 ["Common situations",["New farm: follow Overview from top to bottom.","Existing farm: add current animals and people first, then begin daily records; you do not need to recreate years of history.","Seasonal worker: add the person and use employment status to preserve past work.","Unknown value: leave it blank and update the record when measured; never invent data.","Duplicate record: compare the tag, name and date before deciding which record is correct.","Poor connection: wait for the saved confirmation before closing or submitting again.","Wrong farm information: open the record, verify the source, then correct it.","Shared device: sign out after every shift."]],
 ["Privacy, access and recovery",["Each signed-in user can access only farms where they are a member.","Use a unique password and never share login credentials.","If a person leaves the farm, remove their access promptly while preserving operational records.","If sign-in fails, verify the email address, confirmation message and password before retrying.","If a save fails, your unsaved entry is not treated as a farm record; retry after connectivity returns."]],
];
export default function Help(){return <main className="handbook"><nav className="public-nav"><Link className="brand" href="/"><i>V</i> Verdant</Link><div><Link href="/">Home</Link><Link className="button small" href="/console">Open app</Link></div></nav><header><p className="eyebrow">VERDANT HANDBOOK</p><h1>How to run every part<br/>of your farm workspace.</h1><p>Practical instructions for first setup, daily work, unusual situations, privacy and reliable records.</p></header><div className="book"><aside><b>Contents</b>{chapters.map(([name],i)=><a key={name} href={`#chapter-${i+1}`}>{String(i+1).padStart(2,"0")} {name}</a>)}</aside><article>{chapters.map(([name,items],i)=><section id={`chapter-${i+1}`} key={name}><small>CHAPTER {String(i+1).padStart(2,"0")}</small><h2>{name}</h2><ol>{items.map(item=><li key={item}>{item}</li>)}</ol></section>)}</article></div><section className="help-cta"><h2>Ready to work?</h2><p>Open Verdant and follow the first incomplete setup action.</p><Link className="button" href="/console">Open your farm</Link></section></main>}
