"use client";
import Link from "next/link";import {useLanguage} from "../language";
const en:[string,string[]][]=[
["Getting started",["Create an account from the landing page and confirm your email if asked.","Complete the four setup steps. This creates the farm workspace but no sample records.","Use the Start here checklist on Overview. Each completed item means a real record exists.","Return to Overview at any time to see what is still missing."]],
["Livestock management",["Choose Livestock, then Register animal.","Use a permanent tag or ear-tag number so the animal remains identifiable.","Record current weight and daily feed when known; leave nothing guessed.","Open any animal row to review every saved field.","For sold, deceased or transferred animals, preserve the historic record and update its status instead of creating a duplicate."]],
["Workforce and tasks",["Add every worker once, using the role they actually perform.","Create a task from the Overview setup guide and use a clear action title.","Use Scheduled for future work, In progress while active, Blocked when something prevents completion, and Completed only after verification.","Never place passwords, private medical information, or sensitive payroll details in task notes."]],
["Resource tracking",["Log each meter, delivery, or inventory measurement as a resource reading.","Use consistent zone names, such as North Barn or Well 1.","Always include the exact unit: litres, kWh, kilograms, or another measured unit.","Record readings at consistent intervals before interpreting trends.","A sudden change is a reason to inspect the farm; it is not automatically proof of a fault."]],
["Financial records",["Record sales and other revenue as Income; record purchases, bills, and payroll as Expense.","Use consistent categories so summaries remain meaningful over time.","The counterparty is the supplier, employee, customer, or institution involved.","Verdant is an operating record and does not replace regulated tax or accounting advice."]],
["Using analytics",["Analytics stays empty until operational records exist.","Every displayed total is calculated from your farm records.","Keep units and recording frequency consistent when comparing periods.","Never make an animal-care or financial decision from one measurement alone."]],
["Safe automations",["Give every rule a plain-language name and a specific trigger.","Keep animal treatment, payroll, purchases, and other high-impact actions under human review.","Review a rule whenever the related farm process changes."]],
["Common situations",["New farm: follow Overview from top to bottom.","Existing farm: add current animals and people first, then begin daily records. You do not need to recreate years of history.","Seasonal worker: add the person and preserve their past work when the season ends.","Unknown value: leave it blank and update the record after measuring it. Never invent data.","Duplicate record: compare the tag, name, and date before deciding which record is correct.","Poor connection: wait for confirmation that the record was saved before submitting again.","Wrong information: open the record, verify the source, and then correct it.","Shared device: sign out after every shift."]],
["Privacy, access and recovery",["A signed-in user can access only farms where they are a member.","Use a unique password and never share login credentials.","When a person leaves the farm, remove their access promptly while preserving operational records.","If sign-in fails, verify the email address, confirmation message, and password before retrying.","If saving fails, the unsaved entry is not a farm record. Retry after connectivity returns."]]];
const ar:[string,string[]][]=[
["البدء",["أنشئ حساباً من الصفحة الرئيسية، وأكّد بريدك الإلكتروني إذا طُلب منك ذلك.","أكمل خطوات الإعداد الأربع. يؤدي ذلك إلى إنشاء مساحة عمل المزرعة من دون أي سجلات تجريبية.","استخدم قائمة ابدأ هنا في النظرة العامة. كل عنصر مكتمل يعني وجود سجل حقيقي.","عُد إلى النظرة العامة في أي وقت لمعرفة ما لا يزال ناقصاً."]],
["إدارة الثروة الحيوانية",["اختر الثروة الحيوانية، ثم تسجيل حيوان.","استخدم وسماً دائماً أو رقم قرط حتى يبقى الحيوان قابلاً للتعريف.","سجّل الوزن الحالي والعلف اليومي عندما تكون القيم معروفة، ولا تضع أي تخمينات.","افتح أي صف لحيوان لمراجعة كل حقل محفوظ.","للحيوانات المباعة أو النافقة أو المنقولة، احتفظ بالسجل التاريخي وحدّث حالته بدلاً من إنشاء نسخة مكررة."]],
["فريق العمل والمهام",["أضف كل عامل مرة واحدة، مستخدماً الدور الذي يؤديه فعلياً.","أنشئ مهمة من دليل الإعداد في النظرة العامة، واستخدم عنواناً واضحاً للعمل.","استخدم مجدولة للعمل المستقبلي، وقيد التنفيذ أثناء العمل، ومتوقفة عند وجود عائق، ومكتملة بعد التحقق فقط.","لا تضع كلمات المرور أو المعلومات الطبية الخاصة أو تفاصيل الرواتب الحساسة في ملاحظات المهام."]],
["تتبّع الموارد",["سجّل كل عداد أو تسليم أو قياس للمخزون كقراءة مورد.","استخدم أسماء ثابتة للمناطق، مثل الحظيرة الشمالية أو البئر ١.","أدرج دائماً وحدة القياس الدقيقة: لتر أو كيلوواط ساعة أو كيلوغرام أو أي وحدة مقاسة أخرى.","سجّل القراءات بفترات منتظمة قبل تفسير الاتجاهات.","التغير المفاجئ سبب لفحص المزرعة، لكنه ليس دليلاً تلقائياً على وجود عطل."]],
["السجلات المالية",["سجّل المبيعات والإيرادات الأخرى كدخل، وسجّل المشتريات والفواتير والرواتب كمصروف.","استخدم فئات ثابتة حتى تبقى الملخصات مفيدة مع مرور الوقت.","الطرف المقابل هو المورّد أو الموظف أو العميل أو المؤسسة المعنية.","فيردانت سجل تشغيلي ولا يحل محل الاستشارة الضريبية أو المحاسبية المنظمة."]],
["استخدام التحليلات",["تبقى التحليلات فارغة حتى تتوفر سجلات تشغيلية.","يُحسب كل إجمالي معروض من سجلات مزرعتك.","حافظ على ثبات الوحدات وتكرار التسجيل عند مقارنة الفترات.","لا تتخذ قراراً لرعاية حيوان أو قراراً مالياً اعتماداً على قياس واحد فقط."]],
["الأتمتة الآمنة",["امنح كل قاعدة اسماً واضحاً ومشغّلاً محدداً.","أبقِ علاج الحيوانات والرواتب والمشتريات والإجراءات عالية التأثير الأخرى تحت مراجعة بشرية.","راجع القاعدة كلما تغيرت عملية المزرعة المرتبطة بها."]],
["الحالات الشائعة",["مزرعة جديدة: اتبع النظرة العامة من الأعلى إلى الأسفل.","مزرعة قائمة: أضف الحيوانات والأشخاص الحاليين أولاً، ثم ابدأ السجلات اليومية. لا تحتاج إلى إعادة إنشاء سنوات من التاريخ.","عامل موسمي: أضف الشخص واحتفظ بأعماله السابقة عند انتهاء الموسم.","قيمة غير معروفة: اتركها فارغة وحدّث السجل بعد قياسها. لا تخترع بيانات.","سجل مكرر: قارن الوسم والاسم والتاريخ قبل تحديد السجل الصحيح.","اتصال ضعيف: انتظر تأكيد حفظ السجل قبل الإرسال مرة أخرى.","معلومة خاطئة: افتح السجل وتحقق من المصدر ثم صححها.","جهاز مشترك: سجّل الخروج بعد كل مناوبة."]],
["الخصوصية والوصول والاستعادة",["لا يمكن للمستخدم المسجّل دخوله الوصول إلا إلى المزارع التي هو عضو فيها.","استخدم كلمة مرور فريدة ولا تشارك بيانات تسجيل الدخول.","عند مغادرة شخص للمزرعة، أزل صلاحية وصوله بسرعة مع الاحتفاظ بالسجلات التشغيلية.","إذا فشل تسجيل الدخول، فتحقق من البريد الإلكتروني ورسالة التأكيد وكلمة المرور قبل المحاولة مجدداً.","إذا فشل الحفظ، فلا يُعد الإدخال غير المحفوظ سجلاً للمزرعة. أعد المحاولة بعد عودة الاتصال."]]];
export default function Help(){const {lang}=useLanguage();const chapters=lang==="ar"?ar:en;return <main className="handbook"><nav className="public-nav"><Link className="brand" href="/"><i>V</i> Verdant</Link><div><Link href="/">{lang==="ar"?"الرئيسية":"Home"}</Link><Link className="button small" href="/console">{lang==="ar"?"فتح التطبيق":"Open app"}</Link></div></nav><header><p className="eyebrow">{lang==="ar"?"دليل فيردانت":"VERDANT HANDBOOK"}</p><h1>{lang==="ar"?<>كيفية إدارة كل جزء<br/>من مساحة عمل مزرعتك.</>:<>How to run every part<br/>of your farm workspace.</>}</h1><p>{lang==="ar"?"تعليمات عملية للإعداد الأول والعمل اليومي والحالات غير المعتادة والخصوصية والسجلات الموثوقة.":"Practical instructions for first setup, daily work, unusual situations, privacy and reliable records."}</p></header><div className="book"><aside><b>{lang==="ar"?"المحتويات":"Contents"}</b>{chapters.map(([name],i)=><a key={name} href={`#chapter-${i+1}`}>{String(i+1).padStart(2,"0")} {name}</a>)}</aside><article>{chapters.map(([name,items],i)=><section id={`chapter-${i+1}`} key={name}><small>{lang==="ar"?`الفصل ${i+1}`:`CHAPTER ${String(i+1).padStart(2,"0")}`}</small><h2>{name}</h2><ol>{items.map(item=><li key={item}>{item}</li>)}</ol></section>)}</article></div><section className="help-cta"><h2>{lang==="ar"?"جاهز للعمل؟":"Ready to work?"}</h2><p>{lang==="ar"?"افتح فيردانت واتبع أول خطوة إعداد غير مكتملة.":"Open Verdant and follow the first incomplete setup action."}</p><Link className="button" href="/console">{lang==="ar"?"افتح مزرعتك":"Open your farm"}</Link></section></main>}
