// @ts-nocheck
"use client";
import {useEffect,useMemo,useState} from "react";
import Link from "next/link";
import {createClient} from "../../lib/supabase/client";
import {createFarmWorkspace,createRecord,getCurrentWorkspace,loadFarmData,updateRecord} from "../../lib/supabase/data";

const modules=["Overview","Livestock","Workforce","Resources","Finance","Analytics","Automations"];
const defs={
 Task:{table:"tasks",title:"Tasks",desc:"Work that needs to be done on the farm.",action:"Add task",fields:[["title","Task title"],["description","Instructions"],["status","Status"],["priority","Priority"],["due_at","Due date and time","datetime-local"]]},
 Livestock:{table:"animals",title:"Livestock",desc:"Every animal and its current care information.",action:"Register animal",fields:[["tag_id","Tag / ID"],["display_name","Name"],["species","Species"],["breed","Breed"],["weight_kg","Weight (kg)","number"],["daily_feed_kg","Daily feed (kg)","number"]]},
 Workforce:{table:"employees",title:"Workforce",desc:"Your farm team and the work assigned to them.",action:"Add person",fields:[["full_name","Full name"],["job_title","Role"],["email","Email","email"],["phone","Phone"]]},
 Resources:{table:"resource_readings",title:"Resources",desc:"Actual utility, supply and consumption readings.",action:"Log reading",fields:[["resource_type","Type"],["zone","Area / zone"],["value","Amount","number"],["unit","Unit"],["notes","Notes"]]},
 Finance:{table:"transactions",title:"Finance",desc:"Income and expenses recorded by your farm.",action:"Add transaction",fields:[["direction","Income or expense"],["counterparty","Supplier / customer"],["category","Category"],["amount","Amount","number"],["description","Description"]]},
 Automations:{table:"automations",title:"Automations",desc:"Simple rules for repeatable farm operations.",action:"Create automation",fields:[["name","Rule name"],["trigger_type","When should it run?"]]},
};

export default function Console(){
 const [session,setSession]=useState(undefined),[workspace,setWorkspace]=useState(null),[data,setData]=useState(null),[view,setView]=useState("Overview"),[loading,setLoading]=useState(true),[modal,setModal]=useState(null),[selected,setSelected]=useState(null),[error,setError]=useState("");
 const client=useMemo(()=>createClient(),[]);
 async function refresh(){setLoading(true);try{const ws=await getCurrentWorkspace();setSession(ws?.user||null);setWorkspace(ws?.membership?.farms||null);if(ws?.membership?.farms)setData(await loadFarmData(ws.membership.farms.id));}catch(e){setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{refresh();const {data:s}=client.auth.onAuthStateChange(()=>setTimeout(refresh,0));return()=>s.subscription.unsubscribe()},[]);
 if(loading)return <div className="center-state"><span className="loader"/><p>Loading your farm…</p></div>;
 if(!session)return <Auth onDone={refresh}/>;
 if(!workspace)return <Onboarding onDone={refresh}/>;
 const counts={Livestock:data.animals.length,Workforce:data.employees.length,Resources:data.resource_readings.length,Finance:data.transactions.length,Automations:data.automations.length};
 async function save(table,record){await createRecord(table,{...record,farm_id:workspace.id});setModal(null);await refresh()}
 return <div className="app-shell"><aside className="side"><Link className="brand" href="/"><i>V</i> Verdant</Link><nav>{modules.map(x=><button className={view===x?"active":""} onClick={()=>setView(x)} key={x}><span>{x.slice(0,1)}</span>{x}{counts[x]!==undefined&&<small>{counts[x]}</small>}</button>)}</nav><div className="side-foot"><Link href="/help">? <span>Handbook</span></Link><button onClick={()=>client.auth.signOut()}>↗ <span>Sign out</span></button></div></aside><main className="workspace"><header><div><small>{workspace.name}</small><b>{view}</b></div><button className="avatar">{(session.user_metadata?.full_name||session.email||"U").slice(0,1).toUpperCase()}</button></header>{error&&<p className="error">{error}</p>}{view==="Overview"?<Overview farm={workspace} data={data} go={setView} add={setModal}/>:view==="Analytics"?<Analytics data={data}/>:<Module name={view} rows={data[defs[view].table]} add={()=>setModal(view)} select={setSelected}/>}</main>{modal&&<RecordModal definition={defs[modal]} close={()=>setModal(null)} save={save}/>} {selected&&<Detail item={selected} close={()=>setSelected(null)} />}</div>
}

function Auth(){const [mode,setMode]=useState("login"),[busy,setBusy]=useState(false),[message,setMessage]=useState("");useEffect(()=>{if(location.search.includes("signup"))setMode("signup")},[]);async function submit(e){e.preventDefault();setBusy(true);setMessage("");const form=new FormData(e.currentTarget),email=form.get("email"),password=form.get("password"),full_name=form.get("name");const client=createClient();const result=mode==="signup"?await client.auth.signUp({email,password,options:{data:{full_name}}}):await client.auth.signInWithPassword({email,password});setBusy(false);if(result.error)setMessage(result.error.message);else if(mode==="signup"&&!result.data.session)setMessage("Check your email to confirm your account, then sign in.")}
return <main className="auth"><section><Link className="brand" href="/"><i>V</i> Verdant</Link><div><p className="eyebrow">{mode==="signup"?"START YOUR FARM":"WELCOME BACK"}</p><h1>{mode==="signup"?"Create your account":"Sign in to Verdant"}</h1><p>Your farm records stay private to your workspace.</p><form onSubmit={submit}>{mode==="signup"&&<label>Full name<input name="name" required/></label>}<label>Email address<input name="email" type="email" required/></label><label>Password<input name="password" type="password" minLength={6} required/></label>{message&&<p className="form-message">{message}</p>}<button className="button" disabled={busy}>{busy?"Please wait…":mode==="signup"?"Create account":"Sign in"}</button></form><button className="auth-switch" onClick={()=>setMode(mode==="login"?"signup":"login")}>{mode==="login"?"New to Verdant? Create an account":"Already have an account? Sign in"}</button></div></section><aside><p className="eyebrow">ONE CLEAR WORKSPACE</p><h2>Real farm data.<br/>Nothing invented.</h2><p>Start empty, follow a short setup guide, and build an accurate operating history over time.</p><Link href="/help">Explore the complete handbook →</Link></aside></main>}

function Onboarding({onDone}){const [step,setStep]=useState(0),[form,setForm]=useState({name:"",operationType:"Mixed",acreageBand:"Under 50 acres",teamSize:1,country:"Canada",region:""}),[busy,setBusy]=useState(false),[error,setError]=useState("");const pages=[{title:"Name your workspace",text:"This is the farm name your team will see.",fields:[["name","Farm or operation name"],["country","Country"],["region","Province, state or region"]]},{title:"Describe the operation",text:"We use this only to organize your workspace—not to create pretend data.",fields:[["operationType","Primary operation type"],["acreageBand","Approximate land area"]]},{title:"Set the team size",text:"You can add each person after setup.",fields:[["teamSize","Approximate number of people","number"]]},{title:"Your empty farm is ready",text:"Next, the dashboard will guide you to register animals, add people and log the first records.",fields:[]}];async function next(){if(step<3)return setStep(step+1);setBusy(true);try{await createFarmWorkspace(form);await onDone()}catch(e){setError(e.message);setBusy(false)}}return <main className="onboarding"><aside><Link className="brand" href="/"><i>V</i> Verdant</Link><p>Farm setup</p><ol>{pages.map((p,i)=><li className={i<=step?"done":""} key={p.title}><b>{i+1}</b><span>{p.title}</span></li>)}</ol><Link href="/help">Need help?</Link></aside><section><small>STEP {step+1} OF {pages.length}</small><h1>{pages[step].title}</h1><p>{pages[step].text}</p><div className="onboard-fields">{pages[step].fields.map(([key,label,type])=><label key={key}>{label}<input type={type||"text"} value={form[key]} min="1" onChange={e=>setForm({...form,[key]:type==="number"?Number(e.target.value):e.target.value})}/></label>)}{step===3&&<div className="ready-list"><span>✓ No sample animals or transactions</span><span>✓ Guided first actions</span><span>✓ All modules available</span></div>}</div>{error&&<p className="error">{error}</p>}<div className="onboard-actions">{step>0&&<button onClick={()=>setStep(step-1)}>Back</button>}<button className="button" disabled={busy||step===0&&!form.name.trim()} onClick={next}>{step===3?busy?"Creating…":"Enter dashboard":"Continue"}</button></div></section></main>}

function Overview({farm,data,go,add}){const setup=[{done:data.animals.length>0,title:"Register your first animal",text:"Create the first individual livestock record.",action:()=>add("Livestock")},{done:data.employees.length>0,title:"Add a team member",text:"Build the team before assigning work.",action:()=>add("Workforce")},{done:data.tasks.length>0,title:"Plan today’s work",text:"Create and assign the first farm task.",action:()=>add("Task")},{done:data.resource_readings.length>0,title:"Log a resource reading",text:"Start measuring water, power, feed or fuel.",action:()=>add("Resources")},{done:data.transactions.length>0,title:"Record farm finances",text:"Add the first real income or expense.",action:()=>add("Finance")}];const done=setup.filter(x=>x.done).length;return <div className="page"><div className="page-title"><div><p className="eyebrow">TODAY</p><h1>Good morning.</h1><p>{done===5?"Your farm records are ready for today’s work.":"Finish the setup guide to make this dashboard useful."}</p></div><b className="progress-number">{done}/{setup.length}<small>setup steps</small></b></div><section className="setup"><div className="section-head"><div><h2>Start here</h2><p>Each step creates a real record. Skip anything that does not apply.</p></div><span>{Math.round(done/setup.length*100)}%</span></div><div className="progress"><i style={{width:`${done/setup.length*100}%`}}/></div>{setup.map((x,i)=><button className={x.done?"complete":""} key={x.title} onClick={x.action}><b>{x.done?"✓":i+1}</b><span><strong>{x.title}</strong><small>{x.done?"Complete":x.text}</small></span><em>{x.done?"View":"Start"}</em></button>)}</section><section className="overview-lines"><h2>Farm at a glance</h2>{[["Animals",data.animals.length,"Livestock"],["People",data.employees.length,"Workforce"],["Open tasks",data.tasks.filter(x=>x.status!=="completed").length,"Workforce"],["Resource readings",data.resource_readings.length,"Resources"],["Transactions",data.transactions.length,"Finance"]].map(([label,value,target])=><button key={label} onClick={()=>go(target)}><span>{label}</span><b>{value}</b><em>Open →</em></button>)}</section></div>}

function Module({name,rows,add,select}){const d=defs[name];return <div className="page"><div className="page-title"><div><h1>{d.title}</h1><p>{d.desc}</p></div><button className="button" onClick={add}>+ {d.action}</button></div>{rows.length===0?<Empty name={name} action={d.action} add={add}/>:<section className="data-list"><div className="list-head"><b>{rows.length} {rows.length===1?"record":"records"}</b><span>Newest first</span></div>{rows.map(row=><button key={row.id} onClick={()=>select({type:name,...row})}><span><strong>{row.display_name||row.full_name||row.counterparty||row.name||`${row.resource_type} · ${row.zone}`}</strong><small>{row.tag_id||row.job_title||row.description||row.trigger_type||new Date(row.recorded_at||row.created_at).toLocaleDateString()}</small></span><b>{row.weight_kg?`${row.weight_kg} kg`:row.amount?`${row.direction==="expense"?"−":"+"}$${Number(row.amount).toLocaleString()}`:row.value?`${row.value} ${row.unit}`:row.status||"Active"}</b><em>Open →</em></button>)}</section>}</div>}
function Empty({name,action,add}){return <section className="empty"><span>{name.slice(0,1)}</span><h2>No {name.toLowerCase()} records yet</h2><p>This area stays empty until you add real farm information. Your first record will appear here immediately.</p><button className="button" onClick={add}>+ {action}</button><Link href="/help">How this section works →</Link></section>}
function Analytics({data}){const has=data.animals.length||data.resource_readings.length||data.transactions.length;const income=data.transactions.filter(x=>x.direction==="income").reduce((a,x)=>a+Number(x.amount),0),expense=data.transactions.filter(x=>x.direction==="expense").reduce((a,x)=>a+Number(x.amount),0);return <div className="page"><div className="page-title"><div><h1>Analytics</h1><p>Patterns calculated only from records in your workspace.</p></div></div>{!has?<section className="empty"><span>A</span><h2>No analytics yet</h2><p>Analytics appears after you add livestock, resource, or finance records. Nothing is estimated or invented.</p><Link href="/help">Learn what to record →</Link></section>:<section className="analytics"><div><span>Livestock recorded</span><b>{data.animals.length}</b></div><div><span>Total resource readings</span><b>{data.resource_readings.length}</b></div><div><span>Net recorded cash flow</span><b>${(income-expense).toLocaleString()}</b></div><p>More useful trends appear as you consistently record weights, consumption, production and transactions.</p></section>}</div>}
function RecordModal({definition,close,save}){const [busy,setBusy]=useState(false),[error,setError]=useState("");const choices={species:["cattle","sheep","goat","poultry","horse","other"],resource_type:["water","electricity","feed","fuel","waste","other"],direction:["income","expense"],status:["scheduled","in_progress","blocked","completed"],priority:["low","normal","high","urgent"]};async function submit(e){e.preventDefault();setBusy(true);const values=Object.fromEntries(new FormData(e.currentTarget));definition.fields.filter(x=>x[2]==="number").forEach(x=>values[x[0]]=Number(values[x[0]]));if(definition.table==="transactions")values.transaction_date=new Date().toISOString().slice(0,10);if(definition.table==="automations"){values.trigger_config={};values.actions=[]}try{await save(definition.table,values)}catch(e){setError(e.message);setBusy(false)}}return <div className="modal-back" onMouseDown={e=>e.target===e.currentTarget&&close()}><form className="modal" onSubmit={submit}><div><span><small>NEW RECORD</small><h2>{definition.action}</h2></span><button type="button" onClick={close}>×</button></div>{definition.fields.map(([key,label,type])=><label key={key}>{label}{choices[key]?<select required name={key}>{choices[key].map(x=><option key={x} value={x}>{x.replaceAll("_"," ")}</option>)}</select>:<input required={!['description','notes','breed','phone','email'].includes(key)} name={key} type={type||"text"}/>}</label>)}{error&&<p className="error">{error}</p>}<footer><button type="button" onClick={close}>Cancel</button><button className="button" disabled={busy}>{busy?"Saving…":"Save record"}</button></footer></form></div>}
function Detail({item,close}){return <div className="drawer"><div className="drawer-head"><span><small>{item.type} RECORD</small><h2>{item.display_name||item.full_name||item.name||item.counterparty||"Record details"}</h2></span><button onClick={close}>×</button></div><dl>{Object.entries(item).filter(([k,v])=>!['type','farm_id','metadata','trigger_config','actions'].includes(k)&&v!==null&&v!=="").map(([k,v])=><div key={k}><dt>{k.replaceAll("_"," ")}</dt><dd>{typeof v==="object"?JSON.stringify(v):String(v)}</dd></div>)}</dl><p>Every value shown here comes from this saved farm record.</p></div>}
